import { Token, User } from ".prisma/client";
import { GetServerSideProps, NextApiRequest } from "next";
import { Session } from "next-iron-session";
import Header from "../components/header/Header";
import checkIfTokenValidAndRefresh from "../libs/checkIfTokenValidAndRefresh";
import withSession from "../libs/ironSession";
import { useRouter } from "next/router";
import prisma from "../prisma/prisma";
import { Auction } from "@prisma/client";
// import Categories from "../components/mainPage/categories/categories";
import { Box } from "@chakra-ui/layout";
// import { Button } from "@chakra-ui/button";
// import AuctionMoreFromUser from "../components/auction/AuctionBuyWindow.tsx/AuctionMoreFromUser";
import AuctionGetRandomAuctions from "../components/auction/AuctionBuyWindow.tsx/AuctionGetRandomAuctions";
// import { useDisclosure } from "@chakra-ui/react";

export const getServerSideProps: GetServerSideProps = withSession(
  async function ({ req }: { req: NextApiRequest & { session: Session } }) {
    // return await getUserFromSession(req);

    const auctions = await prisma.auction.findMany();
    // console.log(auctions);
    const token = await checkIfTokenValidAndRefresh(req.session);
    if (token) {
      const user = await prisma.user.findUnique({
        where: { id: token.user.id },
        select: {
          avatar: true,
          firstName: true,
          lastName: true,
          cart: { include: { items: true } },
          id: true,
        },
      });
      if (user) {
        return {
          props: {
            token: token.token,
            user: user,
            auctions: auctions ? auctions : [],
          },
        };
      }
      return {
        props: {
          token: token.token,
          user: token.user,
          auctions: auctions ? auctions : [],
        },
      };
    } else {
      return { props: { token: "", auctions: auctions ? auctions : [] } };
    }
  }
);

export default function Home(
  props: Token & { user?: User } & { auctions: Auction[] }
) {
  const router = useRouter();
  const refreshData = () => {
    router.push(router.asPath);
  };

  return (
    <Box>
      <Header
        user={props.user}
        token={props.token}
        refresh={refreshData}
        // isDrawerOpen={isOpen}
        // onDrawerOpen={onOpen}
        // onDrawerClose={onClose}
      ></Header>
      {/* <Button
        onClick={() => {
          router.push("/auction/krzeslo-komputerowe-2");
        }}
      >
        Testowa aukcja
      </Button> */}
      <AuctionGetRandomAuctions />
      {/* <PickedForYou width="100%" auctionsToShow={props.auctions} /> */}
      {/* <Categories position="center" /> */}
    </Box>
  );
}

// import type { NextPage } from 'next'
// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

// export default Home
